# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.

version: 2
updates:
- package-ecosystem: "" # See documentation for possible values
  directory: "/" # Location of package manifests
  schedule:
    interval: "weekly"
  # Ignore npm updates in /infra
  - package-ecosystem: "npm"
    directory: "/infra"
    ignore:
      - dependency-name: "*"
      
 - package-ecosystem: "npm"
    directories:
    - "/packages"
    - "/packages/reva-admin-react"
    - "/packages/reva-candidate"
    - "/packages/reva-website"
    - "/packages/reva-api"
    # Pas besoin d'anlayser /infra uniquement utilisé pour créer les environnements de dev locaux
    #- "/infra/strapi
    schedule:
      interval: "weekly"
      
  # Enable version updates for Docker
  #- package-ecosystem: "docker-compose"
    # Look for a `Dockerfile` in the `root` directory
    #directory: "/"
    # Pas besoin d'anlayser /infra uniquement utilisé pour créer les environnements de dev locaux
    #directories:
    #- "/infra/elastic"
    #- "/infra/ftps"
    #- "/infra/keycloak"
    #- "/infra/postgres"
    # Check for updates once a week
    #schedule:
    #  interval: "weekly"
