volumes:
  postgres_data:
    driver: local

services:
  postgres:
    image: postgres:13.7
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    ports:
      - 5433:5432
    restart: always
  keycloak:
    restart: always
    image: quay.io/keycloak/keycloak:24.0.2
    volumes:
      - ./themes/francevae:/opt/keycloak/themes/francevae
    environment:
      KC_HEALTH_ENABLED: true
      KC_METRICS_ENABLED: true
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_HOSTNAME: localhost
      KC_PROXY: edge
      # KC_HOSTNAME_STRICT: false
      # KC_HOSTNAME_STRICT_BACKCHANNEL: true
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: password
      REVA_BASE_URL: http://localhost:3000
      KC_HTTP_RELATIVE_PATH: auth
      KC_HTTP_ENABLED: true
      KC_HOSTNAME_STRICT_HTTPS: false
      REVA_URL_CREATE_AAP_ACCOUNT: http://localhost:3002/espace-professionnel/inscription/
      # Uncomment the line below if you want to specify JDBC parameters. The parameter below is just an example, and it shouldn't be used in production without knowledge. It is highly recommended that you read the PostgreSQL JDBC driver documentation in order to use it.
      # JDBC_PARAMS: "ssl=true"
    command:
      - start
      # - --optimized
      - --hostname-port=8888
      - --features=preview
    ports:
      - 8888:8080
    depends_on:
      - postgres
