# route app.region.scalingo.io/ to my-api.region.scalingo.io/

http:
  routers:
    # --- BEGIN STAGING ---

    auth-reva-incubateur-net:
      rule: "Host(`auth.reva.incubateur.net`)"
      service: auth-reva-incubateur-net
      middlewares:
        - removeHeader

    metabase-reva-incubateur-net:
      rule: "Host(`metabase.reva.incubateur.net`)"
      service: metabase-reva-incubateur-net
      middlewares:
        - removeHeader

    site-web:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/`)"
      service: site-web
      middlewares:
        - removeHeader

    espace-pro:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/admin`)"
      service: espace-pro
      middlewares:
        - removeHeader

    app-candidat:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/app`)"
      service: app-candidat
      middlewares:
        - removeHeader

    api:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/graphql`)"
      service: api
      middlewares:
        - removeHeader

    # --- END STAGING ---
    # Enable dashboard on /dashboard with basic auth
    dashboard:
      rule: 'Host(`{{ env "APP" }}.{{ env "REGION_NAME" }}.scalingo.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      service: api@internal
      middlewares:
        - auth
  middlewares:
    removeHeader: # remove double header
      headers:
        customResponseHeaders:
          x-request-id: "" # remove
          strict-transport-security: ""
    auth:
      basicAuth:
        users:
          - '{{ env "BASIC_AUTH_USER_PASSWORD" }}' # htpasswd format  BASIC_AUTH_USER_PASSWORD="test:TODEFINED"
  services:
    # --- BEGIN STAGING ---

    auth-reva-incubateur-net:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://auth-reva-incubateur-net.osc-fr1.scalingo.io/"

    metabase-reva-incubateur-net:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://metabase-reva-incubateur-net.osc-fr1.scalingo.io/"

    site-web:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/"

    espace-pro:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/admin/"

    app-candidat:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/app/"

    api:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/graphql"

    # --- END STAGING ---
