# route app.region.scalingo.io/ to my-api.region.scalingo.io/

http:
  routers:
    # --- BEGIN STAGING ---

    auth-reva-incubateur-net:
      rule: "Host(`auth.reva.incubateur.net`)"
      service: auth-reva-incubateur-net
      middlewares:
        - removeHeader

    metabase-reva-incubateur-net:
      rule: "Host(`metabase.reva.incubateur.net`)"
      service: metabase-reva-incubateur-net
      middlewares:
        - removeHeader

    site-web-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/`)"
      service: site-web-staging
      middlewares:
        - removeHeader

    site-web-staging-subscription:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/inscription-pro`)"
      service: site-web-staging-subscription
      middlewares:
        - removeHeader

    espace-pro-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/admin`)"
      service: espace-pro-staging
      middlewares:
        - removeHeader

    app-candidat-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/app`)"
      service: app-candidat-staging
      middlewares:
        - removeHeader

    api-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/api`)"
      service: api-staging
      middlewares:
        - removeHeader

    # Should be removed after the creation of the /api path
    payment-request-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/payment-request/proof`)"
      service: site-web-staging
      middlewares:
        - removeHeader

    # Should be removed after the creation of the /api path
    ping-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/ping`)"
      service: site-web-staging
      middlewares:
        - removeHeader

    # --- END STAGING ---
    # --- BEGIN PRODUCTION ---

    auth-reva-beta-gouv-fr:
      rule: "Host(`auth.reva.beta.gouv.fr`)"
      service: auth-reva-beta-gouv-fr
      middlewares:
        - removeHeader

    metabase-reva-beta-gouv-fr:
      rule: "Host(`metabase.reva.beta.gouv.fr`)"
      service: metabase-reva-beta-gouv-fr
      middlewares:
        - removeHeader

    site-web-production:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/`)"
      service: site-web-production
      middlewares:
        - removeHeader

    site-web-production-subscription:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/inscription-pro`)"
      service: site-web-production-subscription
      middlewares:
        - removeHeader

    espace-pro-production:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/admin`)"
      service: espace-pro-production
      middlewares:
        - removeHeader

    app-candidat-production:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/app`)"
      service: app-candidat-production
      middlewares:
        - removeHeader

    api-production:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/api`)"
      service: api-production
      middlewares:
        - removeHeader

    # Should be removed after the creation of the /api path
    payment-request-production:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/payment-request/proof`)"
      service: site-web-production
      middlewares:
        - removeHeader

    # Should be removed after the creation of the /api path
    ping-production:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/ping`)"
      service: site-web-production
      middlewares:
        - removeHeader

    # --- END PRODUCTION ---
    # --- BEGIN PRODUCTION 2---

    vae-gouv-main-page:
      rule: "Host(`vae.gouv.fr`)"
      service: framer-vae-gouv-fr-maintenance-page
      middlewares:
        - removeHeader
        - removePath

    auth-vae-gouv-fr:
      rule: "Host(`auth.vae.gouv.fr`)"
      service: auth-vae-gouv-fr
      middlewares:
        - removeHeader

    espace-pro-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/admin`)"
      service: espace-pro-production-2
      middlewares:
        - removeHeader

    app-candidat-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/app`)"
      service: app-candidat-production-2
      middlewares:
        - removeHeader

    api-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/api`)"
      service: api-production-2
      middlewares:
        - removeHeader

    # --- END PRODUCTION 2 ---

    # Enable dashboard on /dashboard with basic auth
    dashboard:
      rule: 'Host(`{{ env "APP" }}.{{ env "REGION_NAME" }}.scalingo.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      service: api@internal
      middlewares:
        - auth
  middlewares:
    removeHeader: # remove double header
      headers:
        customResponseHeaders:
          x-request-id: "" # remove
          strict-transport-security: ""
    removePath:
      replacePath:
        path: "/"

    auth:
      basicAuth:
        users:
          - '{{ env "BASIC_AUTH_USER_PASSWORD" }}' # htpasswd format  BASIC_AUTH_USER_PASSWORD="test:TODEFINED"
  services:
    # --- BEGIN STAGING ---

    auth-reva-incubateur-net:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://auth-reva-incubateur-net.osc-fr1.scalingo.io/"

    metabase-reva-incubateur-net:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://metabase-reva-incubateur-net.osc-fr1.scalingo.io/"

    site-web-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging-website.osc-fr1.scalingo.io/"

    site-web-staging-subscription:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging-website.osc-fr1.scalingo.io/"

    espace-pro-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/admin/"

    app-candidat-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/app/"

    api-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/api"

    # --- END STAGING ---

    # --- BEGIN PRODUCTION ---

    auth-reva-beta-gouv-fr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://auth-reva-beta-gouv-fr.osc-secnum-fr1.scalingo.io/"

    metabase-reva-beta-gouv-fr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://metabase-reva-beta-gouv-fr.osc-secnum-fr1.scalingo.io/"

    site-web-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod.osc-secnum-fr1.scalingo.io/"

    site-web-production-subscription:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-inscription-pro.osc-secnum-fr1.scalingo.io/"

    espace-pro-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod.osc-secnum-fr1.scalingo.io/admin/"

    app-candidat-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod.osc-secnum-fr1.scalingo.io/app/"

    api-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod.osc-secnum-fr1.scalingo.io/api"

    # --- END PRODUCTION ---

    # --- BEGIN PRODUCTION 2---

    framer-vae-gouv-fr-maintenance-page:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://frequent-tool-670208.framer.app/"

    auth-vae-gouv-fr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://auth-reva-beta-gouv-fr.osc-secnum-fr1.scalingo.io/"

    espace-pro-production-2:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-2.osc-secnum-fr1.scalingo.io/admin/"

    app-candidat-production-2:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-2.osc-secnum-fr1.scalingo.io/app/"

    api-production-2:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-2.osc-secnum-fr1.scalingo.io/api"

    # --- END PRODUCTION 2 ---
