# route app.region.scalingo.io/ to my-api.region.scalingo.io/

http:
  routers:
    # --- BEGIN STAGING ---

    auth-reva-incubateur-net:
      rule: "Host(`auth.reva.incubateur.net`)"
      service: auth-reva-incubateur-net
      middlewares:
        - removeHeader

    metabase-reva-incubateur-net:
      rule: "Host(`metabase.reva.incubateur.net`)"
      service: metabase-reva-incubateur-net
      middlewares:
        - removeHeader
        - add-anti-clickjacking-headers

    site-web-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/`)"
      service: site-web-staging
      middlewares:
        - removeHeader
        - add-security-headers

    site-web-staging-subscription:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/inscription-pro`)"
      service: site-web-staging-subscription
      middlewares:
        - removeHeader
        - add-security-headers

    espace-pro-react-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/admin2`)"
      service: espace-pro-react-staging
      middlewares:
        - removeHeader
        - add-security-headers

    app-candidat-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/app`)"
      service: app-candidat-staging
      middlewares:
        - removeHeader
        - add-security-headers

    app-candidate-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/candidat`)"
      service: app-candidate-staging
      middlewares:
        - removeHeader
        - add-security-headers

    api-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/api`)"
      service: api-staging
      middlewares:
        - removeHeader

    # Should be removed after the creation of the /api path
    payment-request-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/payment-request/proof`)"
      service: site-web-staging
      middlewares:
        - removeHeader
        - add-security-headers

    # Should be removed after the creation of the /api path
    ping-staging:
      rule: "Host(`reva.incubateur.net`) && PathPrefix(`/ping`)"
      service: site-web-staging
      middlewares:
        - removeHeader

    # --- END STAGING ---
    # --- BEGIN PRODUCTION REVA.BETA.GOUV.FR---

    site-web-production:
      rule: "Host(`reva.beta.gouv.fr`)"
      service: noop@internal
      middlewares:
        - redirect-vae-gouv-fr

    site-web-production-subscription:
      rule: "Host(`reva.beta.gouv.fr`) && PathPrefix(`/inscription-pro`)"
      service: noop@internal
      middlewares:
        - redirect-inscription-pro

    # --- END PRODUCTION REVA.BETA.GOUV.FR ---
    # --- BEGIN PRODUCTION VAE.GOUV.FR--

    vae-gouv-main-page-www:
      rule: "Host(`www.vae.gouv.fr`)"
      service: noop@internal
      middlewares:
        - redirect-www
        - add-security-headers

    vae-gouv-main-page:
      rule: "Host(`vae.gouv.fr`)"
      service: site-web-production
      middlewares:
        - removeHeader
        - add-security-headers

    auth-vae-gouv-fr:
      rule: "Host(`auth.vae.gouv.fr`)"
      service: auth-vae-gouv-fr
      middlewares:
        - removeHeader

    metabase-vae-gouv-fr:
      rule: "Host(`metabase.vae.gouv.fr`)"
      service: metabase-production
      middlewares:
        - removeHeader
        - add-anti-clickjacking-headers

    espace-pro-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/admin`)"
      service: espace-pro-production-2
      middlewares:
        - removeHeader
        - add-security-headers

    espace-pro-react-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/admin2`)"
      service: espace-pro-react-production
      middlewares:
        - removeHeader
        - add-security-headers

    app-candidat-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/app`)"
      service: app-candidat-production-2
      middlewares:
        - removeHeader
        - add-security-headers

    app-candidate-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/candidat`)"
      service: app-candidate-production
      middlewares:
        - removeHeader
        - add-security-headers

    api-production-vae-gouv-fr:
      rule: "Host(`vae.gouv.fr`) && PathPrefix(`/api`)"
      service: api-production-2
      middlewares:
        - removeHeader

    # --- END PRODUCTION VAE.GOUV.FR ---

    # Enable dashboard on /dashboard with basic auth
    dashboard:
      rule: 'Host(`{{ env "APP" }}.{{ env "REGION_NAME" }}.scalingo.io`) && (PathPrefix(`/api`) || PathPrefix(`/dashboard`))'
      service: api@internal
      middlewares:
        - auth
  middlewares:
    removeHeader: # remove double header
      headers:
        customResponseHeaders:
          x-request-id: "" # remove
          strict-transport-security: ""
    add-anti-clickjacking-headers:
      headers:
        customResponseHeaders:
          Content-Security-Policy: "frame-ancestors 'self';"
          X-Frame-Options: SAMEORIGIN
    add-security-headers:
      headers:
        customResponseHeaders:
          Content-Security-Policy: "frame-ancestors 'self'; object-src 'none';img-src self data: https: ; script-src 'self' https://static.userguiding.com https://public.produktly.com https://matomo.fabrique.social.gouv.fr 'unsafe-inline'"
          X-Frame-Options: SAMEORIGIN

    removePath:
      replacePath:
        path: "/"

    redirect-www:
      redirectRegex:
        regex: "^https?://www\\.(.+)"
        replacement: "https://${1}"
        permanent: true

    redirect-inscription-pro:
      redirectRegex:
        regex: ".*"
        replacement: "https://vae.gouv.fr/espace-professionnel/creation/"
        permanent: true

    redirect-vae-gouv-fr:
      redirectRegex:
        regex: ".*"
        replacement: "https://vae.gouv.fr/"
        permanent: true

    auth:
      basicAuth:
        users:
          - '{{ env "BASIC_AUTH_USER_PASSWORD" }}' # htpasswd format  BASIC_AUTH_USER_PASSWORD="test:TODEFINED"
  services:
    # --- BEGIN STAGING ---

    auth-reva-incubateur-net:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://auth-reva-incubateur-net.osc-fr1.scalingo.io/"

    metabase-reva-incubateur-net:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://metabase-reva-incubateur-net.osc-fr1.scalingo.io/"

    site-web-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging-website.osc-fr1.scalingo.io/"

    site-web-staging-subscription:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging-website.osc-fr1.scalingo.io/"

    espace-pro-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/admin/"

    espace-pro-react-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-admin-react.osc-fr1.scalingo.io/admin2/"

    app-candidat-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/app/"

    app-candidate-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging-candidate.osc-fr1.scalingo.io/candidat/"

    api-staging:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-staging.osc-fr1.scalingo.io/api"

    # --- END STAGING ---

    # --- BEGIN PRODUCTION ---

    framer-reva-beta-gouv-fr-maintenance-page:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://cold-tool-912858.framer.app/"

    site-web-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-website.osc-secnum-fr1.scalingo.io/"

    auth-vae-gouv-fr:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://auth-reva-beta-gouv-fr.osc-secnum-fr1.scalingo.io/"

    metabase-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://metabase-reva-beta-gouv-fr.osc-secnum-fr1.scalingo.io/"

    espace-pro-production-2:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-2.osc-secnum-fr1.scalingo.io/admin/"

    espace-pro-react-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-admin-react.osc-secnum-fr1.scalingo.io/admin2/"

    app-candidat-production-2:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-2.osc-secnum-fr1.scalingo.io/app/"

    app-candidate-production:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-candidate.osc-secnum-fr1.scalingo.io/candidat/"

    api-production-2:
      loadBalancer:
        passHostHeader: false
        servers:
          - url: "https://reva-prod-2.osc-secnum-fr1.scalingo.io/api"

    # --- END PRODUCTION  ---
