name: Cypress tests
on: [push]
env:
  FRAMER_WEBSITE_URL: https://reva.incubateur.net
  REACT_APP_API_GRAPHQL: https://reva.incubateur.net/api/graphql
  REACT_APP_KEYCLOAK_REALM: reva-app
  REACT_APP_KEYCLOAK_URL: https://auth.reva.incubateur.net/
  REACT_APP_KEYCLOAK_CLIENT_ID: reva-app
  # On la definie uniquement pour que le serveur start...
  DATABASE_URL: postgresql://reva:password@localhost:5444/reva?schema=public
jobs:
  cypress-run:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16.x]
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
      - run: npm run build
