name: Lint
on: [push]

jobs:
  eslint-reva-api:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Running ESLint
        run: npm run eslint -w reva-api
  eslint-reva-admin:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/reva-admin-react
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Running ESLint
        run: npm run lint
  eslint-reva-candidate:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/reva-candidate
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Running ESLint
        run: npm run lint
  eslint-reva-website:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/reva-website
    steps:
      - uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20.x
          cache: "npm"
      - name: Installing dependencies
        run: npm ci
      - name: Running ESLint
        run: npm run lint
